Added ability for npcs to move diagonally
xDiaym/poom pull request #11
Opened 2022-01-24 16:26 UTC by BazaroZero

Npc moves straight at player, but when runs into a wall it finds way with help of A* algo

2022-01-24 20:06 UTC, xDiaym requested changes

2022-01-24 20:06 UTC, xDiaym commented on poom/animated.py
> +                image,
black?

2022-01-24 20:06 UTC, xDiaym commented on poom/npc.py
> +        signX = 1 if direction.x > 0 else -1
non pep8 naming

2022-01-24 20:06 UTC, xDiaym commented on poom/npc.py
> +        if self.algo == 0 and self._is_wall:
magic constant

2022-01-24 20:09 UTC, xDiaym commented
Path finding can be incapsulated in new class

2022-01-25 07:51 UTC, BazaroZero commented on poom/animated.py
> +                image,
Yeah

2022-01-25 13:22 UTC, merged